sudo: false
language: scala

scala:
  - 2.10.6
  - 2.11.11
  - 2.12.2

env:
  global:
    - MAIN_SCALA_VERSION=2.11.11

script:
  - project/travis-build.sh
after_success:
  - project/travis-post-build.sh

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt

jdk:
  - oraclejdk8
